market/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(
        template_name='core/login.html',
        authentication_form=LoginForm
    ), name='login'),
]

market/dashboard/urls.py
from django.urls import path
from . import views
app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
]

market/item/urls.py
from django.urls import path
from . import views
app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit', views.edit, name='edit'),
]

market/market/urls.py
# making image display work
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('inbox/', include('conversation.urls')), 
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/dashboard/models.py
from django.db import models

# Create your models here.

market/dashboard/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from item.models import Item

# Create your views here.

@login_required
def dashboard(request):
    items = Item.objects.filter(created_by=request.user)
    return render(request, 'dashboard/dashboard.html', {
        'items': items
    })

market/dashboard/templates/dashboard/dashboard.html
{% extends 'core/base.html' %} {% block title %}Dashboard{% endblock %} 
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Your items</h2>
    <div class="grid grid-cols-4 gap-6">
        {% for item in items %}
        <div
            class="bg-white rounded-xl shadow-sm overflow-hidden hover:shadow-lg transition-shadow duration-300"
        >
            <a href="{% url 'item:detail' item.id %}" class="block">
                <div class="aspect-square overflow-hidden">
                    <img
                        src="{{item.image.url}}"
                        alt="{{item.name}}"
                        class="w-full h-full object-cover rounded-t-xl hover:scale-105 transition-transform duration-300"
                    />
                </div>
            </a>
            <div class="p-6 h-32 flex flex-col justify-between">
                <h3 class="text-xl font-semibold text-gray-800 truncate">
                    {{item.name}}
                </h3>
                <p class="text-lg font-bold text-blue-600">${{item.price}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}