market/conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'
urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

market/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(
        template_name='core/login.html',
        authentication_form=LoginForm
    ), name='login'),
]

market/dashboard/urls.py
from django.urls import path
from . import views
app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
]

market/item/urls.py
from django.urls import path
from . import views
app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit', views.edit, name='edit'),
]

market/market/urls.py
# making image display work
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('inbox/', include('conversation.urls')), 
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'w-full p-3 border rounded-xl'
    }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'w-full p-3 border rounded-xl'
    }))

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'w-full p-3 border rounded-xl'
    }))
    
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        'class': 'w-full p-3 border rounded-xl'
    }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'w-full p-3 border rounded-xl'
    }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full p-3 border rounded-xl'
    }))

market/core/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login
from item.models import Category, Item
from .forms import SignUpForm, LoginForm

# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignUpForm()
    return render(request, 'core/signup.html', {
        'form': form
    })

market/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %}{% endblock %} | usedy</title>
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="min-h-screen flex flex-col">
        <nav
            class="px-6 py-6 flex items-center justify-between border-b border-gray-200"
        >
            <a href="/" class="text-xl font-semibold">usedy</a>
            <div class="space-x-6">
                <a
                    href="{% url 'item:new' %}"
                    class="text-xl font-semibold hover:text-gray-500"
                    >new item</a
                >
                <a
                    href="{% url 'item:items' %}"
                    class="text-xl font-semibold hover:text-gray-500"
                    >browse item</a
                >
                {% if user.is_authenticated %}
                <a
                    href="{% url 'conversation:inbox' %}"
                    class="px-6 py-3 text-xl font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700"
                    >Inbox</a
                >
                <a
                    href="{% url 'dashboard:dashboard' %}"
                    class="px-6 py-3 text-xl font-semibold bg-blue-500 text-white rounded-xl hover:bg-teal-700"
                    >Dashboard</a
                >
                {% else %}
                <a
                    href="{% url 'core:signup' %}"
                    class="px-6 py-3 text-xl font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700"
                    >Sign up</a
                >
                <a
                    href="{% url 'core:login' %}"
                    class="px-6 py-3 text-xl font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700"
                    >Login</a
                >
                {% endif %}
            </div>
        </nav>
        <main class="flex-grow px-6 py-6">
            {% block content %}{% endblock %}
        </main>
        <footer class="mt-auto py-6 px-6 flex justify-between bg-gray-700">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">about</h3>
                <p>
                    Lorem, ipsum dolor sit amet consectetur adipisicing
                    dadadadad adadada aemfjfaofjaohdfhao ing dadadadad adadada
                    aemfjfaofjaohdfhao
                </p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">site map</h3>
                <ul class="space-y-2">
                    <li>
                        <a
                            href="#"
                            class="text-lg text-teal-500 hover:text-teal-700"
                            >About</a
                        >
                    </li>
                    <li>
                        <a
                            href="{% url 'core:contact' %}"
                            class="text-lg text-teal-500 hover:text-teal-700"
                            >Contact</a
                        >
                    </li>
                    <li>
                        <a
                            href="#"
                            class="text-lg text-teal-500 hover:text-teal-700"
                            >Privacy policy</a
                        >
                    </li>
                    <li>
                        <a
                            href="#"
                            class="text-lg text-teal-500 hover:text-teal-700"
                            >Terms of use</a
                        >
                    </li>
                </ul>
            </div>
        </footer>
    </body>
</html>

market/core/templates/core/contact.html
{% extends 'core/base.html' %} 
{% block title %}Contact{% endblock %} 
{% block content %}
<h1 class="text-green-500">Contact page</h1>
{% endblock %}

market/core/templates/core/index.html
{% extends 'core/base.html' %} {% block title %}welcome{% endblock %} 
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Newest items</h2>
    <div class="grid grid-cols-3 gap-6">
        {% for item in items %}
        <div
            class="bg-white rounded-xl shadow-sm overflow-hidden hover:shadow-lg transition-shadow duration-300"
        >
            <a href="#" class="block">
                <div class="aspect-square overflow-hidden">
                    <img
                        src="{{item.image.url}}"
                        alt="{{item.name}}"
                        class="w-full h-full object-cover rounded-t-xl hover:scale-105 transition-transform duration-300"
                    />
                </div>
            </a>
            <div class="p-6 h-32 flex flex-col justify-between">
                <h3 class="text-xl font-semibold text-gray-800 truncate">
                    {{item.name}}
                </h3>
                <p class="text-lg font-bold text-blue-600">${{item.price}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Categories</h2>
    <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
        <div class="p-6 bg-white rounded-xl">
            <h3 class="text-2xl font-semibold">{{category.name}}</h3>
            <p class="text-gray-500">{{category.items.count}} items</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

market/core/templates/core/login.html
{% extends 'core/base.html' %} {% block title %}Login{% endblock %} 
{% block content %}
<div class="w-1/2 text-center my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Login</h1>
    <form method="post" action="." novalid>
        {% csrf_token %}
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br />
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br />
            {{ form.password }}
        </div>
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %} {% for error in field.errors %}
            <p class="text-red-600">{{ error }}</p>
            {% endfor %} {% endfor %} {% for error in form.non_field_errors %}
            <p class="text-red-600">{{ error }}</p>
            {% endfor %}
        </div>
        {% endif %}

        <button
            type="submit"
            class="w-full mt-6 px-8 py-4 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 transition-colors duration-200"
        >
            Login
        </button>
    </form>
</div>
{% endblock %}

market/core/templates/core/signup.html
{% extends 'core/base.html' %} 
{% block title %}Sign Up{% endblock %} 
{% block content %}
<div class="w-1/2 text-center my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>
    <form method="post" action="." novalidate>
        {% csrf_token %}
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br />
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br />
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br />
            {{ form.password1 }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Confirm Password</label><br />
            {{ form.password2 }}
        </div>
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %} 
                {% for error in field.errors %}
                    <p class="text-red-600">{{ error }}</p>
                {% endfor %}
            {% endfor %} 
            {% for error in form.non_field_errors %}
                <p class="text-red-600">{{ error }}</p>
            {% endfor %}
        </div>
        {% endif %}
        
        <button
            type="submit"
            class="w-full mt-6 px-8 py-4 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 transition-colors duration-200"
        >
            Sign up
        </button>
    </form>
</div>
{% endblock %}